### ISSUE TITLE
Sprites changing position

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/desire#32]
Sometimes led appears on the right side and the vacuum robot to the left -- also this happens with the security bot.

Reproduce:
Start game
click on the bin
get your leg
head to the waterhole
click on it so that the text plays.
talk to the vaccum robot.

![Image](https://user-images.githubusercontent.com/11029768/214319128-0a06555b-b742-4830-be41-f8258cdd7923.png)

**Comment by DerekGooding** [comment]
The issue is, LED always faces right so if he doesn't speak first in the dialogue, he won't be on the left hand side. I've added a small "are you okay" line to the start of this conversation so he speaks first. 

I also noticed the same issue when speaking with the captain. Investigating now

**Comment by DerekGooding** [comment]
Fixed the captain scenes by including a blank speaking for LED so he speaks first.

**Comment by alexitsios** [comment]
The issue persists with the security robot as well. Also, when the vacuum robot speaks first, it's on the left side.
